CREATE DATABASE Cliente;
USE Cliente;


CREATE TABLE TBL_CLIENTE (
	ID_CLIENTE BIGINT PRIMARY KEY IDENTITY NOT NULL,
	TX_NOME VARCHAR(40) NOT NULL,
	TX_CPF VARCHAR(14) NOT NULL,
	TX_EMAIL VARCHAR(70) NOT NULL,
	TX_TELEFONE VARCHAR(11) NOT NULL,
	BO_VALIDADO BIT NOT NULL
);

CREATE TABLE TBL_ENTREGA (
	NUM_ID BIGINT PRIMARY KEY IDENTITY NOT NULL,
	TX_CEP VARCHAR(8) NOT NULL,
	TX_ENDERECO VARCHAR(50) NOT NULL,
	TX_COMPLEMENTO VARCHAR(30) NOT NULL
);

ALTER TABLE TBL_ENTREGA
ADD ID_CLIENTE BIGINT NOT NULL;

ALTER TABLE TBL_ENTREGA
ADD CONSTRAINT FK_ID_CLIENTE
FOREIGN KEY (ID_CLIENTE)
REFERENCES TBL_CLIENTE (ID_CLIENTE);

ALTER TABLE TBL_ENTREGA
ADD FK_ID_PEDIDO BIGINT NOT NULL;

ALTER TABLE TBL_ENTREGA
ADD FK_ID_ENT BIGINT NOT NULL;